"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[₪](bold green)'
error_symbol = '[₪](bold red)'
vimcmd_symbol = '[₪](bold green)' 
vimcmd_replace_one_symbol = '[₪](bold purple)' 
vimcmd_replace_symbol = '[₪](bold purple)' 
vimcmd_visual_symbol = '[₪](bold yellow)'

[directory]
format = 'in [$path]($style)[$read_only]($read_only_style) '
truncation_symbol = '…/'
truncate_to_repo = false

[nix_shell]
impure_msg = ""
symbol = "*"

[shlvl]
threshold = 3
symbol = "»"
disabled = false

[status]
format = '[$status ]($style)'
disabled = false

[git_metrics]
disabled = false

[rust]
disabled = true

[direnv]
disabled = false

